# Generated by Django 4.1 on 2022-08-31 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoTajeta',
            new_name='TipoTarjeta',
        ),
    ]
