# Generated by Django 4.1 on 2022-08-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_DNI', models.CharField(max_length=10, null=True)),
                ('customer_name', models.CharField(max_length=50, null=True)),
                ('customer_surname', models.CharField(max_length=50, null=True)),
                ('branch_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
